### ISSUE TITLE
Particle iOS SDK version

### ISSUE THREAD

**Issue by mcgouganp** [EddyVerbruggen/nativescript-particle#5]
The particle iOS SDK version has advanced from what is currently used by this plugin. Is it possible for this to be updated.

**Comment by EddyVerbruggen** [comment]
Absolutely. Interesting in doing a PR? Otherwise it may take a while.

**Comment by mcgouganp** [comment]
I'll give it a shot.

**Comment by mcgouganp** [comment]
Done. Thanks Eddy.
