### ISSUE TITLE
Images missing in Setup Wizard (iOS)

### ISSUE THREAD

**Issue by mcgouganp** [EddyVerbruggen/nativescript-particle#8]
To replicate:
 * get the repository
 * build the demo app
 * click "Add" button which starts Setup wizard

Images are available in the POD.

Only tested on iOS.

**Comment by EddyVerbruggen** [comment]
I can see what you mean, but I have no explanation for those images to not show up..

**Comment by mcgouganp** [comment]
I think perhaps a recent (?) Nativescript update has fixed this.
I've just noticed that all of a sudden this problem has gone away.
I can't explain it, but .... yay?
